### ISSUE TITLE
Question: How do I actually navigate from screen A to B?

### ISSUE THREAD

**Issue by raamcosta** [MatrixDev/ComposableRoutes#1]
From the readme I now the code, but how do I get a `navController` inside the Screen Composable?

Usually, we pass a lambda to the Composable that is "implemented" in the `NavHost` level, but that seems to not be possible with the `register` route method.

**Comment by MatrixDev** [comment]
Hey.
I usually use providers for it (IMHO this is more Compose-like style).

Declare somewhere in the code:
```kotlin
val LocalNavController = compositionLocalOf<NavHostController> {
    error("NavController not present")
}
```

And than when you create your navController:
```kotlin
    val navController = rememberNavController()
    CompositionLocalProvider(LocalNavController provides navController) {
        NavHost(navController = navController, startDestination = NavRoutes.JoinAsGuestScreen()) {
            NavRoutes.registerAll(this)
        }
    }
```

To use it:
```kotlin
LocalNavController.current.navigate...
```

I probably should add come shortcuts to the library in order to support it, but don't know yet how to make it easy enough.

**Comment by MatrixDev** [comment]
@raamcosta, I've added this to the README.md as a `How to pass NavController to my Screen?` chapter. Thanks for noticing :)

**Comment by raamcosta** [comment]
Well, I should know, I also have my own annotation processor that is actually very similar to yours 😄 
I'll leave the link just so you can take a look.
https://github.com/raamcosta/compose-destinations
